### ISSUE TITLE
Ghidra

### ISSUE THREAD

**Issue by subbassbro** [rjwalls/2019-spring-cs4401-notes#23]
I think having a writeup on how to use Ghidra and using it on a binary would be super useful

**Comment by rjwalls** [comment]
Good idea, any volunteers want to write up a tutorial or find a link to a good existing tutorial?

**Comment by subbassbro** [comment]
I am working on a tutorial/writeup of some basic features of Ghidra. There is a chance it will get done by class time on Thursday. Most likely it will be published and pushed by class time on Monday.

**Comment by rjwalls** [comment]
Closing given lack of progress.
