### ISSUE TITLE
Lecture Notes => Binaries

### ISSUE THREAD

**Issue by amandaeze97** [rjwalls/2019-spring-cs4401-notes#24]
Specify which binaries apply to which lecture notes (for each). For example, "Lecture Notes: Basics of Shellcoding" can be used to solve Stack4.

**Comment by rjwalls** [comment]
The current plan is to implement this making some infrastructure changes and adding new yaml front matter to each post (e.g., the "challenges" key).

**Comment by rjwalls** [comment]
Closing given lack of progress.
