### ISSUE TITLE
Create index to find stack and heap concepts faster

### ISSUE THREAD

**Issue by JGrycel** [rjwalls/2019-spring-cs4401-notes#28]

**Comment by rjwalls** [comment]
Can you describe what you envision this index to look like?

**Comment by JGrycel** [comment]
I'm picturing a notes page with a list of concepts (where they are, how they grow, what is the stack pointer, where are variables, where are arguments, frames, etc ). And then each item in the list points to other relevant notes ( ex: argument vs variable placement is linked to string format attacks). I can always make this myself...

**Comment by rjwalls** [comment]
While I can see some value is an outline or table of contents,  I'd hesitate to create a full index unless we can do it automatically. Especially since `grep` would probably work pretty well in place of an index.

**Comment by rjwalls** [comment]
Closing given lack of progress.
