### ISSUE TITLE
Notes are dense

### ISSUE THREAD

**Issue by kqsavell** [rjwalls/2019-spring-cs4401-notes#29]
For some notes like the global offset table and format strings it is difficult to figure out the application of the content, even given the examples.

**Comment by kqsavell** [comment]
Maybe linking example videos or other content would be helpful, since personally I don't learn well from reading but by example.

**Comment by rjwalls** [comment]
I've added some preamble text to both the GOT and format strings notes to make it more clear how these articles fit into the flow of the course. 

You'll also notice that both articles already have a number of links at the bottom for finding more information; those links even include a few videos.

**Comment by rjwalls** [comment]
We will also be looking at the other articles to see if we can make improvements.
