### ISSUE TITLE
Linux command toolkit/cheatsheet

### ISSUE THREAD

**Issue by gkmacneal** [rjwalls/2019-spring-cs4401-notes#30]
Requesting a note page for a list of Linux commands that are useful for solving the binaries. This can be similar to the GDB cheatsheet. Commands could include strings and grep. Preferably, each would have at least a bit of explanation on how to use it effectively.

**Comment by rjwalls** [comment]
This is a good idea.

@gkmacneal Perhaps, you'd be willing to get us started and add some notes for strings and grep?

**Comment by rjwalls** [comment]
Closing given lack of progress.
