### ISSUE TITLE
GDB TUI

### ISSUE THREAD

**Issue by brandon-m-navarro** [rjwalls/2019-spring-cs4401-notes#32]
When first looking at the assembly for a problem, I found the _layout_ (asm/split) commands to be pretty useful. A link to how to fully navigate GDB's TUI mode can be found [here](https://sourceware.org/gdb/onlinedocs/gdb/TUI-Commands.html).

**Comment by rjwalls** [comment]
@brandon-m-navarro Perhaps you'd be willing to add this information to the GDB notes page?

**Comment by rjwalls** [comment]
Closing given lack of progress.
